### ISSUE TITLE
Demo not working in mobile 

### ISSUE THREAD

**Issue by daaajo** [czarpino/angular-image-cropper#3]
The demo provided here: https://cdn.rawgit.com/czarpino/angular-image-cropper/5ba830bb4e94d4c014d1edf681d140fb1ea29b57/demo.html
dont work in mobile (iPhone, Android) I can not "swipe" over the image to change the crop...

**Comment by czarpino** [comment]
Hi @daaajo. I forgot to update the `README` with the link to the updated version of the cropper. Demo should be working fine now. :)
